In [2]:
import tensorflow as tf
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd


In [3]:
df= pd.read_csv('data.csv')
df

Breathing Problem Fever Dry Cough Sore throat Running Nose Asthma  \
0                  Yes   Yes       Yes         Yes          Yes     No   
1                  Yes   Yes       Yes         Yes           No    Yes   
2                  Yes   Yes       Yes         Yes          Yes    Yes   
3                  Yes   Yes       Yes          No           No    Yes   
4                  Yes   Yes       Yes         Yes          Yes     No   
...                ...   ...       ...         ...          ...    ...   
5429               Yes   Yes        No         Yes          Yes    Yes   
5430               Yes   Yes       Yes          No          Yes    Yes   
5431               Yes   Yes       Yes          No           No     No   
5432               Yes   Yes       Yes          No          Yes     No   
5433               Yes   Yes       Yes          No          Yes    Yes   

     Chronic Lung Disease Headache Heart Disease Diabetes  ... Fatigue   \
0                      No       No            No      Yes  ...      Yes   
1                     Yes      Yes            No       No  ...      Yes   
2                     Yes      Yes            No      Yes  ...      Yes   
3                      No       No           Yes      Yes  ...       No   
4                     Yes      Yes           Yes      Yes  ...       No   
...                   ...      ...           ...      ...  ...      ...   
5429                  Yes       No            No       No  ...      Yes   
5430                   No      Yes            No      Yes  ...      Yes   
5431                   No       No           Yes       No  ...       No   
5432                   No      Yes           Yes       No  ...       No   
5433                   No      Yes            No      Yes  ...      Yes   

     Gastrointestinal  Abroad travel Contact with COVID Patient  \
0                  Yes            No                        Yes   
1                   No            No                         No   
2                  Yes           Yes                         No   
3                   No           Yes                         No   
4                  Yes            No                        Yes   
...                ...           ...                        ...   
5429               Yes            No                         No   
5430                No            No                         No   
5431                No            No                         No   
5432                No            No                         No   
5433                No            No                         No   

     Attended Large Gathering Visited Public Exposed Places  \
0                          No                           Yes   
1                         Yes                           Yes   
2                          No                            No   
3                         Yes                           Yes   
4                          No                           Yes   
...                       ...                           ...   
5429                       No                            No   
5430                       No                            No   
5431                       No                            No   
5432                       No                            No   
5433                       No                            No   

     Family working in Public Exposed Places Wearing Masks  \
0                                        Yes            No   
1                                         No            No   
2                                         No            No   
3                                         No            No   
4                                         No            No   
...                                      ...           ...   
5429                                      No            No   
5430                                      No            No   
5431                                      No            No   
5432                             

In [18]:

df.replace('Yes',1,inplace=True)

In [19]:
df

Breathing Problem  Fever  Dry Cough  Sore throat  Running Nose  Asthma  \
0                     1      1          1            1             1       0   
1                     1      1          1            1             0       1   
2                     1      1          1            1             1       1   
3                     1      1          1            0             0       1   
4                     1      1          1            1             1       0   
...                 ...    ...        ...          ...           ...     ...   
5429                  1      1          0            1             1       1   
5430                  1      1          1            0             1       1   
5431                  1      1          1            0             0       0   
5432                  1      1          1            0             1       0   
5433                  1      1          1            0             1       1   

      Chronic Lung Disease  Headache  Heart Disease  Diabetes  ...  Fatigue   \
0                        0         0              0         1  ...         1   
1                        1         1              0         0  ...         1   
2                        1         1              0         1  ...         1   
3                        0         0              1         1  ...         0   
4                        1         1              1         1  ...         0   
...                    ...       ...            ...       ...  ...       ...   
5429                     1         0              0         0  ...         1   
5430                     0         1              0         1  ...         1   
5431                     0         0              1         0  ...         0   
5432                     0         1              1         0  ...         0   
5433                     0         1              0         1  ...         1   

      Gastrointestinal   Abroad travel  Contact with COVID Patient  \
0                     1              0                           1   
1                     0              0                           0   
2                     1              1                           0   
3                     0              1                           0   
4                     1              0                           1   
...                 ...            ...                         ...   
5429                  1              0                           0   
5430                  0              0                           0   
5431                  0              0                           0   
5432                  0              0                           0   
5433                  0              0                           0   

      Attended Large Gathering  Visited Public Exposed Places  \
0                            0                              1   
1                            1                              1   
2                            0                              0   
3                            1                              1   
4                            0                              1   
...                        ...                            ...   
5429                         0                              0   
5430                         0                              0   
5431                         0                              0   
5432                         0                              0   
5433                         0                              0   

      Family working in Public Exposed Places  Wearing Masks  \
0                                           1              0   
1                                           0              0   
2                                           0              0   
3                                           0              0   
4                                           0              0   
...                                       ...            ...   
5429          

In [20]:
df.to_numpy()

array([[1, 1, 1, ..., 0, 0, 1],
       [1, 1, 1, ..., 0, 0, 1],
       [1, 1, 1, ..., 0, 0, 1],
       ...,
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0]], dtype=int64)

In [22]:
narray= df.to_numpy()

In [42]:
narray

array([[1, 1, 1, ..., 0, 0, 1],
       [1, 1, 1, ..., 0, 0, 1],
       [1, 1, 1, ..., 0, 0, 1],
       ...,
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0]], dtype=int64)

In [45]:
Y_train=narray[:,-1:]

In [46]:
Y_train

array([[1],
       [1],
       [1],
       ...,
       [0],
       [0],
       [0]], dtype=int64)

In [47]:
len(Y_train)

5434

In [27]:
len(narray)

5434

In [48]:
Y_train

array([[1],
       [1],
       [1],
       ...,
       [0],
       [0],
       [0]], dtype=int64)

In [49]:
X_train= np.delete(narray,-1,axis=1)

In [50]:
X_train

array([[1, 1, 1, ..., 1, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       ...,
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0]], dtype=int64)

In [64]:
model = tf.keras.models.Sequential([
    
    tf.keras.layers.Dense(units=20, activation='relu'),
    tf.keras.layers.Dense(units=13, activation='relu'),
    tf.keras.layers.Dense(units=1, activation='sigmoid')
])

In [65]:
model

In [66]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [67]:
model.fit(X_train, Y_train, epochs=6)

Epoch 1/6
170/170 [==============================] - 1s 2ms/step - loss: 0.4412 - accuracy: 0.7790
Epoch 2/6
170/170 [==============================] - 0s 2ms/step - loss: 0.1632 - accuracy: 0.9431
Epoch 3/6
170/170 [==============================] - 0s 2ms/step - loss: 0.1013 - accuracy: 0.9639
Epoch 4/6
170/170 [==============================] - 0s 2ms/step - loss: 0.0818 - accuracy: 0.9704
Epoch 5/6
170/170 [==============================] - 0s 2ms/step - loss: 0.0716 - accuracy: 0.9731
Epoch 6/6
170/170 [==============================] - 0s 2ms/step - loss: 0.0670 - accuracy: 0.9731


In [85]:
sample=np.array([[1,1,1,1,0,0,0,0,0,1,1,1,0,0,0,0,0,0,0,0]])
np.shape(sample)
len(sample)


1

In [87]:
pred =model.predict(sample)
if(pred[0][0]>0.5):
    print("Likely to have covid")
else:
    print("Unlikely to get covid")

1/1 [==============================] - 0s 11ms/step
Likely to have covid


In [88]:
import pickle

In [90]:
pickle.dump(model, open('model.sav', 'wb'))

Keras weights file (<HDF5 file "variables.h5" (mode r+)>) saving:
...layers\dense
......vars
.........0
.........1
...layers\dense_1
......vars
.........0
.........1
...layers\dense_2
......vars
.........0
.........1
...metrics\mean
......vars
.........0
.........1
...metrics\mean_metric_wrapper
......vars
.........0
.........1
...optimizer
......vars
.........0
.........1
.........10
.........11
.........12
.........2
.........3
.........4
.........5
.........6
.........7
.........8
.........9
...vars
Keras model archive saving:
File Name                                             Modified             Size
config.json                                    2023-01-21 21:08:15         1795
metadata.json                                  2023-01-21 21:08:15           64
variables.h5                                   2023-01-21 21:08:15        31040
